// Generate two fresh TESTNET wallets (A = sender, B = recipient) and write them to .env.
// Run: npm run gen
import { ethers } from "ethers";
import * as fs from "node:fs";
import * as path from "node:path";

const A = ethers.Wallet.createRandom();
const B = ethers.Wallet.createRandom();

console.log("Generated two fresh TESTNET-ONLY wallets:\n");
console.log("Wallet A (sender)");
console.log("  address:    ", A.address);
console.log("  privateKey: ", A.privateKey);
console.log("Wallet B (recipient)");
console.log("  address:    ", B.address);
console.log("  privateKey: ", B.privateKey);

const envPath = path.resolve(process.cwd(), ".env");
if (fs.existsSync(envPath)) {
  console.log(`\n.env already exists at ${envPath} — NOT overwriting.`);
  console.log("Edit it by hand if you want to use these new keys.");
} else {
  const content =
    [
      "# TESTNET-ONLY wallets generated by `npm run gen`. NEVER commit this file.",
      `PRIVATE_KEY_A=${A.privateKey}`,
      `WALLET_A_ADDRESS=${A.address}`,
      `PRIVATE_KEY_B=${B.privateKey}`,
      `WALLET_B_ADDRESS=${B.address}`,
      "",
      "# Optional RPC overrides:",
      "# ARC_RPC_URL=https://rpc.testnet.arc.network",
      "# BASE_SEPOLIA_RPC_URL=https://sepolia.base.org",
      "",
    ].join("\n");
  fs.writeFileSync(envPath, content, { mode: 0o600 });
  console.log(`\nWrote ${envPath} (gitignored).`);
}

console.log("\nNext steps:");
console.log("  1. Fund Wallet A with test USDC: https://faucet.circle.com (select Arc Testnet)");
console.log("  2. Run the transfer:            npm run arc");
